
```{r}
library(tidyverse)
```

```{r}
files <- list.files("./planillasc_csv/", pattern = "\\.csv$", full.names = TRUE)

# Cargar los archivos y agregar la columna con el nombre del archivo
df <- map_dfr(files, ~ read_csv(.x, col_types = cols()) %>% mutate(filename = basename(.x))) %>% 
  select(propietario = filename, sp = Especies) %>% 
  separate(sp, into = c("nombre_comun", "nombre_cientifico"), sep = " \\(", extra = "merge") %>% 
  mutate(propietario = gsub("\\.csv$", "", propietario),
         nombre_cientifico = gsub("\\)$", "", nombre_cientifico)) %>% 
  separate(nombre_cientifico, into = c("genero", "especie"), sep = " ", extra = "merge", remove = FALSE)

rm(files)
```

```{r}
library(rredlist)
library(dplyr)
Sys.setenv(IUCN_REDLIST_KEY = "")
```

```{r}
species_df <- df %>% 
  select(genero, especie) %>% 
  distinct()

res <- rl_species_latest("Cerdocyon", "thous")
res$red_list_category$code
res$taxon$family_name
res$taxon$order_name
```

```{r}
get_species_data <- function(genero, especie) {
  Sys.sleep(1)  # Pausa de 1 segundo entre peticiones
  
  res <- tryCatch(
    rl_species_latest(genero, especie),
    error = function(e) {
      message(paste("Error al procesar", genero, especie, ":", e$message))
      return(NULL)
    }
  )
  
  if (!is.null(res)) {
    return(data.frame(
      genero = genero,
      especie = especie,
      code = res$red_list_category$code,
      family = res$taxon$family_name,
      order = res$taxon$order_name,
      res_list = I(list(res)),
      stringsAsFactors = FALSE
    ))
  } else {
    return(data.frame(
      genero = genero,
      especie = especie,
      code = NA,
      family = NA,
      order = NA,
      res_list = I(list(NULL)),
      stringsAsFactors = FALSE
    ))
  }
}

# Aplicar la función a cada fila del dataframe
df_res <- species_df %>%
  rowwise() %>%
  do(get_species_data(.$genero, .$especie)) %>%
  ungroup()

saveRDS(df_res, file = "res_data.rds")
```

```{r}
library(stringr)
df_res <- readRDS("res_data.rds")
df_res <- df_res %>% mutate(family = str_to_title(family),
                  order = str_to_title(order),
                  nombre_cientifico = paste0(genero, " ", especie)) %>% 
  select(orden = order, familia = family, genero, especie, nombre_cientifico, codigo = code, res_list)

df_csv <- df %>% left_join(df_res) %>% 
  select(propietario, nombre_comun, nombre_cientifico, orden, familia, codigo)

write_csv(df_csv, file = "results.csv")
```



